package com.hibernate.dominio;
// Generated 24/08/2016 21:16:44 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Asesinos generated by hbm2java
 */
@Entity
@Table(name="asesinos"
    ,schema="public"
)
@FilterDef(name="asesinosFilter", parameters=
		@ParamDef( name="maxcantasesinatos", type="java.lang.Integer" )
		
)
@Filter(name="asesinosFilter", condition="personasasesinadas >= :maxcantasesinatos")
public class Asesinos  implements java.io.Serializable {


     private int idasesino;
     private Tipoasesinato tipoasesinato;
     private String nombre;
     private Integer edad;
     private Integer personasasesinadas;

    public Asesinos() {
    }

	
    public Asesinos(int idasesino) {
        this.idasesino = idasesino;
    }
    public Asesinos(int idasesino, Tipoasesinato tipoasesinato, String nombre, Integer edad, Integer personasasesinadas) {
       this.idasesino = idasesino;
       this.tipoasesinato = tipoasesinato;
       this.nombre = nombre;
       this.edad = edad;
       this.personasasesinadas = personasasesinadas;
    }
   
     @Id 

    
    @Column(name="idasesino", nullable=false)
    public int getIdasesino() {
        return this.idasesino;
    }
    
    public void setIdasesino(int idasesino) {
        this.idasesino = idasesino;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idasesinato")
    public Tipoasesinato getTipoasesinato() {
        return this.tipoasesinato;
    }
    
    public void setTipoasesinato(Tipoasesinato tipoasesinato) {
        this.tipoasesinato = tipoasesinato;
    }

    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="edad")
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }

    
    @Column(name="personasasesinadas")
    public Integer getPersonasasesinadas() {
        return this.personasasesinadas;
    }
    
    public void setPersonasasesinadas(Integer personasasesinadas) {
        this.personasasesinadas = personasasesinadas;
    }




}


